const LANGUAGE_KEY = "primo-landscaping-language";

const translations = {
  en: {
    brandHomeLabel: "Primo Landscaping home",
    menuLabel: "Open menu",
    languageLabel: "Language selection",
    navHome: "Home",
    navServices: "Services",
    navGalleryReviews: "Gallery & Reviews",
    navContact: "Contact",
    navSchedule: "Schedule",
    heroBadge: "Licensed, bonded, free estimates",
    heroText: "Primo work at a primo price. Reliable lawn care, landscaping, irrigation, hardscape, and seasonal property services for homes and businesses.",
    callPhone: "Call 360-661-3635",
    requestConsultation: "Request a Consultation",
    storyTitle: "Local work with family pride.",
    storyText: "Primo Landscaping was started to give neighbors a dependable crew for the outdoor jobs that make a property feel cared for. What began with lawn maintenance grew into full-service landscaping, irrigation, pavers, fencing, and gravel work built around honest estimates and a clean finish.",
    trustEstimateTitle: "Free Estimates",
    trustEstimateText: "Clear project scopes before work begins.",
    trustResidentialTitle: "Residential & Commercial",
    trustResidentialText: "Routine maintenance and larger outdoor upgrades.",
    trustSeasonTitle: "Year-Round Help",
    trustSeasonText: "Irrigation clean outs, snow-ready equipment, and seasonal care.",
    whatWeHandle: "What we handle",
    homeServicesTitle: "Lawn care, landscape installs, irrigation, and outdoor improvements.",
    homeServicesText: "From clean weekly upkeep to durable paver, concrete, and gravel work, the site is built around practical services customers actually search for.",
    viewServices: "View Services",
    lawnLandscapeCare: "Lawn & Landscape Care",
    lawnLandscapeCareText: "Mowing, edging, pruning, trimming, mulch refreshes, planting, bed cleanup, and general property care.",
    irrigationSystems: "Irrigation Systems",
    irrigationSystemsText: "New irrigation systems, sprinkler repairs, seasonal checks, and winter irrigation clean outs.",
    hardscapeWork: "Hardscape & Property Work",
    hardscapeWorkText: "Fencing, concrete, pavers, gravel driveways, pathways, edging, and curb appeal upgrades.",
    whyEyebrow: "Why should you choose Primo?",
    whyTitle: "A practical crew, a fair price, and a yard that looks finished.",
    whyText: "Customers call Primo because they want outdoor work handled with care, clear communication, and the kind of detail that makes the property easier to enjoy.",
    clearEstimates: "Clear Estimates",
    clearEstimatesText: "You get a straightforward scope before work starts, so expectations are set early.",
    usefulExperience: "Useful Experience",
    usefulExperienceText: "The team can handle routine lawn care and bigger projects like irrigation, pavers, fencing, and gravel.",
    cleanFinish: "Clean Finish",
    cleanFinishText: "Fresh edges, tidy beds, and thoughtful cleanup help the finished project feel professional.",
    yearRoundHelp: "Year-Round Help",
    yearRoundHelpText: "Seasonal services keep properties ready for wet weather, winter clean outs, and spring growth.",
    primoPrice: "Primo job, at a primo price.",
    easyTitle: "Easy to call, easy to schedule, easy to trust.",
    easyText: "The site keeps the phone number, estimate offer, licensing and bonding note, and consultation request within quick reach from every page.",
    easyPoint1: "Call buttons work on mobile phones.",
    easyPoint2: "Consultation form gathers the details needed for a follow-up.",
    easyPoint3: "Gallery uses all provided business and landscape images.",
    bookConsultation: "Book a Consultation",
    seeWork: "See the Work",
    snapshots: "Project snapshots",
    snapshotsTitle: "Clean lawns, fresh beds, sharp edges, useful outdoor spaces.",
    openGallery: "Open Gallery",
    ctaTitle: "Ready for a cleaner, easier-to-maintain property?",
    ctaText: "Call now or send the consultation form and the business can follow up with availability.",
    requestEstimate: "Request Estimate",
    footerLicensed: "Licensed, bonded, and available for free estimates.",
    footerLicensedShort: "Licensed, bonded, free estimates.",
    footerContact: "Contact",
    footerPages: "Pages",
    footerCall: "Call",
    footerNext: "Next",
    footerContactText: "Call or request a consultation for outdoor work.",
    scheduleConsultation: "Schedule a consultation",
    servicesHeroTitle: "Outdoor work handled from grass to gravel.",
    servicesHeroText: "Choose routine lawn care, a fresh landscape refresh, or a practical upgrade that makes the property easier to use and maintain.",
    serviceLawnTitle: "Lawn Care & Maintenance",
    serviceLawnText: "Routine mowing, edging, trimming, cleanup, and detail work to keep yards crisp and presentable. This is a good fit for weekly upkeep, one-time cleanup, or pre-sale curb appeal.",
    serviceLawnButton: "Schedule Lawn Care",
    serviceLandscapeTitle: "Landscape Design & Refreshes",
    serviceLandscapeText: "Planting beds, mulch, shrub shaping, seasonal color, tree and hedge work, and curb appeal projects that make the home feel cared for from the street.",
    serviceLandscapeButton: "Plan a Landscape Refresh",
    serviceIrrigationText: "New irrigation systems, sprinkler troubleshooting, coverage improvements, and winter irrigation clean out service to protect the system when seasons change.",
    serviceIrrigationButton: "Request Irrigation Help",
    servicePaversTitle: "Concrete & Pavers",
    servicePaversText: "Walkways, patios, borders, paver features, and concrete improvements that make outdoor areas easier to use and cleaner to maintain.",
    servicePaversButton: "Ask About Pavers",
    serviceFencingTitle: "Fencing",
    serviceFencingText: "Fence projects for privacy, safety, curb appeal, and cleaner property lines. A consultation can help define layout, access, and material choices.",
    serviceFencingButton: "Discuss Fencing",
    serviceGravelTitle: "Gravel Driveways",
    serviceGravelText: "Gravel driveway installation, refreshes, grading support, and practical property access improvements that help reduce mud and define parking areas.",
    serviceGravelButton: "Price a Gravel Driveway",
    estimateEyebrow: "How estimates work",
    estimateTitle: "Straightforward consultations for small fixes and bigger plans.",
    estimateText: "Customers can describe the property, preferred timing, and the service they need. The business can then follow up by phone to confirm scope and availability.",
    estimatePoint1: "Residential and commercial properties.",
    estimatePoint2: "One-time projects or recurring maintenance.",
    estimatePoint3: "Seasonal work, including irrigation clean out.",
    processEyebrow: "Process",
    processTitle: "Simple steps from first call to finished yard.",
    process1Title: "Call or Request",
    process1Text: "Reach the team at 360-661-3635 or send the consultation form.",
    process2Title: "Walk the Property",
    process2Text: "Review goals, access, measurements, materials, and maintenance needs.",
    process3Title: "Confirm Scope",
    process3Text: "Agree on the service plan, estimate, and schedule before work begins.",
    process4Title: "Primo Finish",
    process4Text: "Complete the work cleanly and leave the property looking cared for.",
    galleryHeroTitle: "Landscape photos with practical curb appeal.",
    galleryHeroText: "Use this page as a portfolio for lawn care, planting beds, seasonal work, trucks, and outdoor improvement examples.",
    capCommercial: "Commercial service setup",
    capSeasonal: "Seasonal property equipment",
    capFrontBeds: "Fresh front yard beds",
    capGarden: "Full garden curb appeal",
    capHedge: "Hedge and shrub care",
    capMulch: "Mulch bed refresh",
    capPathway: "Pathway and planting layout",
    capFlowerBeds: "Colorful flower beds",
    capRockGarden: "Rock garden detail",
    capFieldMowing: "Large-area mowing",
    capYardMowing: "Residential mowing",
    capHedgeTrim: "Tall hedge trimming",
    capDetailTrim: "Detailed hedge care",
    capCleanup: "Yard cleanup",
    capIrrigation: "Irrigation coverage",
    capPaverInstall: "Paver installation",
    capFencing: "Fence installation",
    capGravel: "Gravel driveway work",
    sampleReviews: "Sample reviews",
    reviewsTitle: "Friendly, clear, and easy to recommend.",
    reviewsIntro: "These are placeholder reviews for the draft website and should be replaced with real customer feedback before launch.",
    stars: "5 out of 5 stars",
    review1: "\"They cleaned up our beds, refreshed the mulch, and made the whole front yard look sharp again. The estimate was clear and the crew was easy to work with.\"",
    review1By: "Sample review from M. Jensen",
    review2: "\"Primo Landscaping handled our irrigation clean out before the cold weather hit. Fast response, fair price, and everything was explained well.\"",
    review2By: "Sample review from Carla R.",
    review3: "\"We needed mowing, edging, and some hedge trimming before listing our home. The yard looked tidy and professional when they were done.\"",
    review3By: "Sample review from Daniel P.",
    galleryCtaTitle: "Want your property to look this dialed in?",
    galleryCtaText: "Share a few photos and the service you need through the consultation form.",
    callNow: "Call Now",
    startRequest: "Start Request",
    contactHeroTitle: "Schedule a landscaping consultation.",
    contactHeroText: "Call the business directly or send the form with the service, property type, and preferred timing.",
    talkTitle: "Talk with Primo Landscaping.",
    talkText: "For the fastest response, call the phone number below. You can also use the form to collect consultation details before following up.",
    phoneLabel: "Phone",
    estimateLabel: "Estimate",
    businessLabel: "Business",
    commonWorkLabel: "Common work",
    freeEstimatesAvailable: "Free estimates available",
    commonWorkText: "Lawn care, landscaping, irrigation, fencing, concrete, pavers, gravel driveways",
    requestFormText: "Share the basics and the business can follow up to confirm details.",
    nameLabel: "Name",
    emailLabel: "Email",
    serviceLabel: "Service",
    chooseService: "Choose a service",
    optionLawn: "Lawn care",
    optionLandscape: "Landscape refresh",
    optionIrrigation: "Irrigation system",
    optionWinter: "Winter irrigation clean out",
    optionPavers: "Concrete or pavers",
    optionGravel: "Gravel driveway",
    optionOther: "Other outdoor project",
    propertyType: "Property Type",
    propertyResidential: "Residential",
    propertyCommercial: "Commercial",
    propertyRental: "Rental or multi-property",
    preferredTiming: "Preferred Timing",
    timingSoon: "As soon as possible",
    timingWeek: "This week",
    timingMonth: "This month",
    timingAhead: "Planning ahead",
    projectDetails: "Project Details",
    detailsPlaceholder: "Tell us about the yard, project size, access notes, and what you want done.",
    sendRequest: "Send Consultation Request",
    formNote: "Connect this form to your preferred email or form service before publishing it as a live contact form.",
    popupTitle: "Choose your language",
    popupText: "Select the language you prefer for Primo Landscaping.",
    popupEnglish: "English",
    popupSpanish: "Español"
  },
  es: {
    brandHomeLabel: "Inicio de Primo Landscaping",
    menuLabel: "Abrir menú",
    languageLabel: "Selección de idioma",
    navHome: "Inicio",
    navServices: "Servicios",
    navGalleryReviews: "Galería y Reseñas",
    navContact: "Contacto",
    navSchedule: "Agendar",
    heroBadge: "Con licencia, asegurado, estimados gratis",
    heroText: "Un trabajo primo a un precio primo. Servicio confiable de césped, jardinería, riego, hardscape y mantenimiento de temporada para hogares y negocios.",
    callPhone: "Llamar al 360-661-3635",
    requestConsultation: "Solicitar una consulta",
    storyTitle: "Trabajo local con orgullo familiar.",
    storyText: "Primo Landscaping nació para dar a los vecinos un equipo confiable para los trabajos exteriores que hacen que una propiedad se vea cuidada. Lo que comenzó con mantenimiento de césped creció hasta incluir jardinería completa, riego, adoquines, cercas y grava, siempre con estimados claros y un acabado limpio.",
    trustEstimateTitle: "Estimados gratis",
    trustEstimateText: "Alcances claros antes de comenzar el trabajo.",
    trustResidentialTitle: "Residencial y comercial",
    trustResidentialText: "Mantenimiento regular y mejoras exteriores más grandes.",
    trustSeasonTitle: "Ayuda todo el año",
    trustSeasonText: "Limpieza de riego, equipo para temporada fría y cuidado de temporada.",
    whatWeHandle: "Lo que hacemos",
    homeServicesTitle: "Cuidado de césped, instalación de jardines, riego y mejoras exteriores.",
    homeServicesText: "Desde mantenimiento semanal hasta trabajos duraderos de adoquines, concreto y grava, el sitio se enfoca en servicios prácticos que los clientes buscan.",
    viewServices: "Ver servicios",
    lawnLandscapeCare: "Cuidado de césped y jardín",
    lawnLandscapeCareText: "Corte, bordeado, poda, recorte, renovación de mulch, siembra, limpieza de camas y cuidado general de la propiedad.",
    irrigationSystems: "Sistemas de riego",
    irrigationSystemsText: "Sistemas nuevos de riego, reparación de aspersores, revisiones de temporada y limpieza de riego para invierno.",
    hardscapeWork: "Hardscape y trabajo exterior",
    hardscapeWorkText: "Cercas, concreto, adoquines, entradas de grava, caminos, bordes y mejoras de apariencia.",
    whyEyebrow: "¿Por qué elegir Primo?",
    whyTitle: "Un equipo práctico, precio justo y un jardín bien terminado.",
    whyText: "Los clientes llaman a Primo porque quieren trabajo exterior con cuidado, buena comunicación y detalles que hacen la propiedad más fácil de disfrutar.",
    clearEstimates: "Estimados claros",
    clearEstimatesText: "Recibe un alcance directo antes de comenzar, para que las expectativas estén claras.",
    usefulExperience: "Experiencia útil",
    usefulExperienceText: "El equipo puede manejar cuidado regular de césped y proyectos grandes como riego, adoquines, cercas y grava.",
    cleanFinish: "Acabado limpio",
    cleanFinishText: "Bordes frescos, camas ordenadas y buena limpieza hacen que el proyecto se vea profesional.",
    yearRoundHelp: "Servicio todo el año",
    yearRoundHelpText: "Los servicios de temporada preparan las propiedades para lluvia, limpieza de invierno y crecimiento de primavera.",
    primoPrice: "Trabajo primo, a precio primo.",
    easyTitle: "Fácil de llamar, fácil de agendar, fácil de confiar.",
    easyText: "El sitio mantiene el teléfono, la oferta de estimado, la nota de licencia y seguro, y la solicitud de consulta al alcance en cada página.",
    easyPoint1: "Los botones de llamada funcionan en teléfonos móviles.",
    easyPoint2: "El formulario de consulta reúne los detalles necesarios para dar seguimiento.",
    easyPoint3: "La galería usa las imágenes del negocio y de jardinería proporcionadas.",
    bookConsultation: "Agendar una consulta",
    seeWork: "Ver trabajos",
    snapshots: "Ejemplos de proyectos",
    snapshotsTitle: "Céspedes limpios, camas frescas, bordes definidos y espacios exteriores útiles.",
    openGallery: "Abrir galería",
    ctaTitle: "¿Listo para una propiedad más limpia y fácil de mantener?",
    ctaText: "Llame ahora o envíe el formulario de consulta y el negocio podrá responder con disponibilidad.",
    requestEstimate: "Solicitar estimado",
    footerLicensed: "Con licencia, asegurado y disponible para estimados gratis.",
    footerLicensedShort: "Con licencia, asegurado, estimados gratis.",
    footerContact: "Contacto",
    footerPages: "Páginas",
    footerCall: "Llamar",
    footerNext: "Siguiente",
    footerContactText: "Llame o solicite una consulta para trabajos exteriores.",
    scheduleConsultation: "Agendar una consulta",
    servicesHeroTitle: "Trabajo exterior desde el césped hasta la grava.",
    servicesHeroText: "Elija mantenimiento regular, una renovación del jardín o una mejora práctica que haga la propiedad más fácil de usar y mantener.",
    serviceLawnTitle: "Cuidado y mantenimiento de césped",
    serviceLawnText: "Corte, bordeado, recorte, limpieza y detalles para mantener el jardín presentable. Ideal para mantenimiento semanal, limpieza única o mejorar la apariencia antes de vender.",
    serviceLawnButton: "Agendar cuidado de césped",
    serviceLandscapeTitle: "Diseño y renovación de jardines",
    serviceLandscapeText: "Camas de plantas, mulch, forma de arbustos, color de temporada, árboles, setos y proyectos que mejoran la vista desde la calle.",
    serviceLandscapeButton: "Planear renovación",
    serviceIrrigationText: "Sistemas nuevos de riego, solución de problemas de aspersores, mejoras de cobertura y limpieza de riego para proteger el sistema cuando cambia la temporada.",
    serviceIrrigationButton: "Solicitar ayuda con riego",
    servicePaversTitle: "Concreto y adoquines",
    servicePaversText: "Caminos, patios, bordes, detalles con adoquines y mejoras de concreto que hacen las áreas exteriores más útiles y fáciles de mantener.",
    servicePaversButton: "Preguntar por adoquines",
    serviceFencingTitle: "Cercas",
    serviceFencingText: "Proyectos de cercas para privacidad, seguridad, apariencia y límites más claros. Una consulta ayuda a definir diseño, acceso y materiales.",
    serviceFencingButton: "Hablar de cercas",
    serviceGravelTitle: "Entradas de grava",
    serviceGravelText: "Instalación, renovación y apoyo de nivelación para entradas de grava y mejoras prácticas de acceso que ayudan a reducir lodo y definir estacionamiento.",
    serviceGravelButton: "Cotizar entrada de grava",
    estimateEyebrow: "Cómo funcionan los estimados",
    estimateTitle: "Consultas sencillas para arreglos pequeños y planes grandes.",
    estimateText: "Los clientes pueden describir la propiedad, el horario preferido y el servicio que necesitan. El negocio puede responder por teléfono para confirmar alcance y disponibilidad.",
    estimatePoint1: "Propiedades residenciales y comerciales.",
    estimatePoint2: "Proyectos únicos o mantenimiento recurrente.",
    estimatePoint3: "Trabajo de temporada, incluyendo limpieza de riego.",
    processEyebrow: "Proceso",
    processTitle: "Pasos simples desde la primera llamada hasta el jardín terminado.",
    process1Title: "Llamar o solicitar",
    process1Text: "Comuníquese al 360-661-3635 o envíe el formulario de consulta.",
    process2Title: "Revisar la propiedad",
    process2Text: "Se revisan metas, acceso, medidas, materiales y necesidades de mantenimiento.",
    process3Title: "Confirmar alcance",
    process3Text: "Se acuerda el plan de servicio, estimado y horario antes de comenzar.",
    process4Title: "Acabado Primo",
    process4Text: "Se completa el trabajo con limpieza y una propiedad bien cuidada.",
    galleryHeroTitle: "Fotos de jardinería con apariencia práctica.",
    galleryHeroText: "Use esta página como portafolio de cuidado de césped, camas de plantas, trabajo de temporada, equipos y ejemplos de mejoras exteriores.",
    capCommercial: "Equipo para servicio comercial",
    capSeasonal: "Equipo de temporada",
    capFrontBeds: "Camas frontales frescas",
    capGarden: "Jardín con buena presentación",
    capHedge: "Cuidado de setos y arbustos",
    capMulch: "Renovación de mulch",
    capPathway: "Camino y diseño de plantas",
    capFlowerBeds: "Camas de flores coloridas",
    capRockGarden: "Detalle de jardín con roca",
    capFieldMowing: "Corte de áreas grandes",
    capYardMowing: "Corte residencial",
    capHedgeTrim: "Recorte de setos altos",
    capDetailTrim: "Detalle en setos",
    capCleanup: "Limpieza de jardín",
    capIrrigation: "Cobertura de riego",
    capPaverInstall: "Instalación de adoquines",
    capFencing: "Instalación de cercas",
    capGravel: "Trabajo de entrada de grava",
    sampleReviews: "Reseñas de muestra",
    reviewsTitle: "Amable, claro y fácil de recomendar.",
    reviewsIntro: "Estas son reseñas temporales para el borrador del sitio y deben reemplazarse con opiniones reales antes de publicar.",
    stars: "5 de 5 estrellas",
    review1: "\"Limpiaron nuestras camas, renovaron el mulch y dejaron el frente de la casa muy bien. El estimado fue claro y el equipo fue fácil de tratar.\"",
    review1By: "Reseña de muestra de M. Jensen",
    review2: "\"Primo Landscaping hizo la limpieza del sistema de riego antes del frío. Respuesta rápida, precio justo y todo fue bien explicado.\"",
    review2By: "Reseña de muestra de Carla R.",
    review3: "\"Necesitábamos corte, bordeado y recorte de setos antes de vender la casa. El jardín quedó ordenado y profesional.\"",
    review3By: "Reseña de muestra de Daniel P.",
    galleryCtaTitle: "¿Quiere que su propiedad se vea así de bien?",
    galleryCtaText: "Comparta algunas fotos y el servicio que necesita por medio del formulario.",
    callNow: "Llamar ahora",
    startRequest: "Iniciar solicitud",
    contactHeroTitle: "Agende una consulta de jardinería.",
    contactHeroText: "Llame directamente o envíe el formulario con el servicio, tipo de propiedad y horario preferido.",
    talkTitle: "Hable con Primo Landscaping.",
    talkText: "Para una respuesta más rápida, llame al número abajo. También puede usar el formulario para reunir detalles de la consulta.",
    phoneLabel: "Teléfono",
    estimateLabel: "Estimado",
    businessLabel: "Negocio",
    commonWorkLabel: "Trabajo común",
    freeEstimatesAvailable: "Estimados gratis disponibles",
    commonWorkText: "Cuidado de césped, jardinería, riego, cercas, concreto, adoquines, entradas de grava",
    requestFormText: "Comparta la información básica y el negocio podrá responder para confirmar detalles.",
    nameLabel: "Nombre",
    emailLabel: "Correo electrónico",
    serviceLabel: "Servicio",
    chooseService: "Elija un servicio",
    optionLawn: "Cuidado de césped",
    optionLandscape: "Renovación de jardín",
    optionIrrigation: "Sistema de riego",
    optionWinter: "Limpieza de riego para invierno",
    optionPavers: "Concreto o adoquines",
    optionGravel: "Entrada de grava",
    optionOther: "Otro proyecto exterior",
    propertyType: "Tipo de propiedad",
    propertyResidential: "Residencial",
    propertyCommercial: "Comercial",
    propertyRental: "Renta o varias propiedades",
    preferredTiming: "Horario preferido",
    timingSoon: "Lo antes posible",
    timingWeek: "Esta semana",
    timingMonth: "Este mes",
    timingAhead: "Planificando con tiempo",
    projectDetails: "Detalles del proyecto",
    detailsPlaceholder: "Cuéntenos sobre el jardín, tamaño del proyecto, acceso y lo que quiere hacer.",
    sendRequest: "Enviar solicitud de consulta",
    formNote: "Conecte este formulario a su correo o servicio de formularios preferido antes de publicarlo.",
    popupTitle: "Elija su idioma",
    popupText: "Seleccione el idioma que prefiere para Primo Landscaping.",
    popupEnglish: "English",
    popupSpanish: "Español"
  }
};

function setLanguage(lang) {
  if (!translations[lang]) return;
  const dictionary = translations[lang];

  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (dictionary[key]) element.textContent = dictionary[key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const key = element.getAttribute("data-i18n-placeholder");
    if (dictionary[key]) element.setAttribute("placeholder", dictionary[key]);
  });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => {
    const key = element.getAttribute("data-i18n-aria-label");
    if (dictionary[key]) element.setAttribute("aria-label", dictionary[key]);
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    const isActive = button.getAttribute("data-lang") === lang;
    button.setAttribute("aria-pressed", String(isActive));
    button.classList.toggle("active", isActive);
  });
  localStorage.setItem(LANGUAGE_KEY, lang);
}

function showLanguageDialog() {
  const dialog = document.createElement("div");
  dialog.className = "language-modal";
  dialog.innerHTML = `
    <div class="language-dialog" role="dialog" aria-modal="true" aria-labelledby="language-dialog-title">
      <h2 id="language-dialog-title" data-i18n="popupTitle">Choose your language</h2>
      <p data-i18n="popupText">Select the language you prefer for Primo Landscaping.</p>
      <div class="language-dialog-actions">
        <button class="btn btn-primary" type="button" data-popup-lang="en" data-i18n="popupEnglish">English</button>
        <button class="btn btn-accent" type="button" data-popup-lang="es" data-i18n="popupSpanish">Español</button>
      </div>
    </div>
  `;
  document.body.appendChild(dialog);
  dialog.querySelectorAll("[data-popup-lang]").forEach((button) => {
    button.addEventListener("click", () => {
      setLanguage(button.getAttribute("data-popup-lang"));
      dialog.remove();
      document.querySelector(".brand")?.focus();
    });
  });
  dialog.querySelector("[data-popup-lang]")?.focus();
}

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.getAttribute("data-lang")));
  });

  const savedLanguage = localStorage.getItem(LANGUAGE_KEY);
  if (translations[savedLanguage]) {
    setLanguage(savedLanguage);
  } else {
    setLanguage("en");
    showLanguageDialog();
  }
});
